### ISSUE TITLE
Sync for cloud/local folders

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#134]
We don't currently support any `sync` API. Even with `upload_to` and `download_from`, we will never delete files.

I'm not sure that we need/want to do anything about this, but wanted to capture some thoughts as I considered it. There are two options that I could see being reasonable:

 - **Explicitly document sync as a non-goal** - Add to documentation and link to tools that sync cloud/local
 - **Add a `sync` API** - we can probably do this just with `copytree` + removing files that don't exist on the source. That said, I don't think we want to be a sync tool so we should document this is for convenience, not performance.

**Comment by analog-cbarber** [comment]
You definitely should add sync, otherwise you force users to have to get it from somewhere else. I am pretty sure that at least S3 and Azure both support it in their client API.

**Comment by ypicard** [comment]
AWS S3 supports it with their CLI, but not with the `boto3` SDK, which makes it a key feature that I would love to see happen in this library.

**Comment by pjbull** [comment]
Duplicate of #14. Consolidating.
