### ISSUE TITLE
How to use cloudpathlib for accessing custom S3 installations? 

### ISSUE THREAD

**Issue by YevheniiSemendiak** [drivendataorg/cloudpathlib#136]
For instance, I've deployed MinIO to my cluster and have its endpoint URL.
The only solution that comes to my mind is to instantiate CloudPath with a boto3 client, authenticated to this endpoint.
Am I correct with this assumption?

**Comment by jayqi** [comment]
I'm not familiar with MinIO. Is this documentation describing something similar your situation and how you'd access your S3 with boto3? https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html

**Comment by YevheniiSemendiak** [comment]
@jayqi just posted a PR #137 as an example for it
