### ISSUE TITLE
Add `ignore` argument to `copytree` that lets one filter stuff out

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#145]
`shutil.copytree` has an `ignore` argument that lets one filter stuff out. Would be nice to support that too, but maybe it can be a future enhnacement. 

https://docs.python.org/3/library/shutil.html#shutil.copytree

_Originally posted by @jayqi in https://github.com/drivendataorg/cloudpathlib/pull/142#discussion_r634894383_

--------

Seems like `shutil` just supports callables, and we may even just be able to point users to the same pattern constructor: https://docs.python.org/3/library/shutil.html#shutil.ignore_patterns

**Comment by aaossa** [comment]
Is this issue still available? If that's the case I could work on this.

Seems like applying the filter in this section should do the trick right?

https://github.com/drivendataorg/cloudpathlib/blob/203f6aabad66881fa5301afc327f6435bcd01f71/cloudpathlib/cloudpath.py#L778-L786

Python does something similar I think, by iterating the paths and ignoring those that must be ignored. Relevant code:

* Using the ignore callable to retrieve set of ignored names: https://github.com/python/cpython/blob/a4ac14faa5c2be433738dfbbed14b0eaa1a2399e/Lib/shutil.py#L456
* USing the output of the callable to skip ignored names: https://github.com/python/cpython/blob/a4ac14faa5c2be433738dfbbed14b0eaa1a2399e/Lib/shutil.py#L464-L466

About the callable that defines which objects to ignore, seems like Python's implementation is already good enough, maybe just use the same object (i.e., use the `shutil` version)? Relevant Python source code: https://github.com/python/cpython/blob/a4ac14faa5c2be433738dfbbed14b0eaa1a2399e/Lib/shutil.py#L441-L451

**Comment by pjbull** [comment]
@aaossa Thanks for digging in here. First pass read of what you outlined seems right to me, thanks. Happy to take a PR with an implementation like that. Thanks!

**Comment by aaossa** [comment]
Sure, I'll be working on this in the upcoming days 👌

**Comment by aaossa** [comment]
Created the PR with the proposed implementation in #272 . Every test is passed, including two tests added to confirm that the argument works as expected.

**Comment by pjbull** [comment]
Merged into the main branch, thanks!

**Comment by noamsgl** [comment]
Could not find the `ignore` argument in the Documentation (https://cloudpathlib.drivendata.org/v0.6/api-reference/cloudpath/#cloudpathlib.cloudpath.CloudPath.copytree)
Is there a reason this was left out?

**Comment by jayqi** [comment]
Hi @noamsgl, this is only available in [v0.11.0](https://github.com/drivendataorg/cloudpathlib/blob/master/HISTORY.md#v0110-2022-12-18) and higher. You linked to the v0.6 version of the docs. There's a menu that lets you change the version at the top left of the documentation website.
