### ISSUE TITLE
Confirm that all backends properly iterate over directories

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#15]
Most cloud services don't have a notion of a "directory." We try to add this back in within our logic by doing our own path splitting.

We should make sure that the pathlib methods (`glob` and `iterdir`) and our methods do the same thing of:
 - Returning directories and/or files when iterating
 - Returning the root or current directory when being asked to iter or not
 - Sort order of the returned results (may not be possible/worth it since we use a generator)

**Comment by karolzlot** [comment]
For at least S3 it works differently than in-built Path: it includes also current folder. 

It should be fixed.
