### ISSUE TITLE
ENH: Allow .resolve() with CloudPaths

### ISSUE THREAD

**Issue by remi-braun** [drivendataorg/cloudpathlib#151]
Hello,

In order to simplify the code and unify the API, would it be possible to allow the .resolve() function to CloudPaths, even if this function does nothing ?

To go from:
```python
path = AnyPath(path)
if not isinstance(path, CloudPath):
   path = path.resolve()
```

to 

```python
path = AnyPath(path).resolve()
```

Thanks a lot

**Comment by pjbull** [comment]
We already have a `_resolve` method that we use to make sure there are no relative paths in the key part of the `CloudPath`. Seems reasonable to expose this functionality in the `.resolve` method:
https://github.com/drivendataorg/cloudpathlib/blob/25ff7838dca890766e3ddc2b2143a014ae037f6a/cloudpathlib/cloudpath.py#L846-L868

The tricky part will be to get all the test cases included for this kind of functionality. (E.g., path that ends in `..`, `..` that goes above the bucket level, etc.)

**Comment by remi-braun** [comment]
For sure these moot points can be tricky, however do they really happen when handling cloud paths ? (especially since the `relative_to` function is not implemented)
Maybe just add a warning in the documentation first, and deal with this if the users are asking 😛

**Comment by pjbull** [comment]
Added as a no-op for API consistency in #230
