### ISSUE TITLE
Method to delete local cache

### ISSUE THREAD

**Issue by jayqi** [drivendataorg/cloudpathlib#153]
If you're processing a lot of data in a loop and want to reclaim disk space after you're done with one path, then it could be helpful to have a way to delete the locally cached file. I don't think this should cause any problems because other methods that use the cache will check if it exists and download. 

Currently, one can do this with `cloud_path._local.unlink()` but it would be better to have a method in the public API for this.

**Comment by pjbull** [comment]
Consolidated to #10
