### ISSUE TITLE
Add stable docs page that matches latest released version

### ISSUE THREAD

**Issue by klwetstone** [drivendataorg/cloudpathlib#158]
Github code for `S3Client` has an argument for `boto3_transfer_config`, but inputting that kwarg throws the error:
`TypeError: __init__() got an unexpected keyword argument 'boto3_transfer_config'`

The change that added the `boto3_transfer_config` arg was pushed after the most recent release date, so it's in the docs but not in the package release.

**Comment by jayqi** [comment]
This is something we haven't done before yet for any of our projects, so it will take a little work to figure out how to set up. 

The way to do this is to use the [mike](https://github.com/jimporter/mike) tool. mkdocs-material, which we use for our documentation website, [added native integration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) this recently-ish (February) with mike. However, mike is designed with manual deploys and assumes hosting with GitHub pages, so there will need to be some experimentation to figure out how to get this to (a) work in GitHub Actions CI and (b) work with our Netlify hosting.
