### ISSUE TITLE
conda distribution only available for python 3.9

### ISSUE THREAD

**Issue by analog-cbarber** [drivendataorg/cloudpathlib#159]
See https://github.com/conda-forge/cloudpathlib-feedstock/issues/11

If you try to install from conda-forge into a non-python 3.9 environment, the latest available version is 0.1.1.

This is a serious usability issue. Installation via pip is not sufficient because pip dependencies cannot be added to conda packages.

Unless there is some reason that you need to build the package separate for each platform or version of python, the easiest fix would be to make the conda recipe a [noarch python](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#architecture-independent-packages) recipe so that the same conda package can be installed on any platform or version of python.

**Comment by jayqi** [comment]
Thank you for calling additional attention to https://github.com/conda-forge/cloudpathlib-feedstock/issues/11. I'm going to close this issue in favor of keeping discussion in one place. Please respond to https://github.com/conda-forge/cloudpathlib-feedstock/issues/11 with any additional questions or comments.
