### ISSUE TITLE
AzureBlobPath should implement rename

### ISSUE THREAD

**Issue by analog-cbarber** [drivendataorg/cloudpathlib#162]
If the underlying storage account type is Data Lake Gen2, then it is possible to rename blobs and directory trees without having to resort to copying all the blobs.

The current default implementation of `rename` in `CloudPath` simply redirects to replace`:

```python
    def rename(self, target: "CloudPath") -> "CloudPath":
        # for cloud services replace == rename since we don't just rename,
        # we actually move files
        return self.replace(target)
```

Instead it should actually rename the resource if supported.

**Comment by jayqi** [comment]
I think this is part of #161 since it's an ADLS-Gen2-specific difference.
