### ISSUE TITLE
CloudPath.iterdir should use yield from

### ISSUE THREAD

**Issue by analog-cbarber** [drivendataorg/cloudpathlib#175]
https://github.com/drivendataorg/cloudpathlib/blob/3af76b9b9d8e44a0094248673e5a9b3934f6863f/cloudpathlib/cloudpath.py#L327-L329

It would be more efficient to write:

```python
def iterdir(self) -> Iterable["CloudPath"]:
   yield from self.client._list_dir(self, recursive=False)
```

**Comment by pjbull** [comment]
🤷  IMO not worth tracking in an issue. If someone made this change as part of a substantive PR that would be fine
