### ISSUE TITLE
S3Path.exists() returns True on partial matches

### ISSUE THREAD

**Issue by maciejb** [drivendataorg/cloudpathlib#208]
S3Path.exists() is returning True for anything that begins with the same as a real file. For instance, if we have a file named `foobar`, we get a false positive when querying for `foo`.

```
>>> S3Path('s3://my-bucket/foobar').exists()  # This file is really there
True
>>> S3Path('s3://my-bucket/foo').exists()  # This file does NOT exist
True
```

**Comment by jayqi** [comment]
Looks like this is a bug in `S3Client._s3_file_query`.

https://github.com/drivendataorg/cloudpathlib/blob/2084e205a86691b94b738df0b7ced351efedc3c8/cloudpathlib/s3/s3client.py#L154-L165

This branch of logic is too permissive and needs to also check if there's a `/`. 

Also a blind spot in our tests that this isn't caught.

**Comment by pjbull** [comment]
> This branch of logic is too permissive and needs to also check if there's a /.

I think append a `/` to the key if there isn't one in this fallback path—that said, we'll need to double check if that handles the fake directory scenario as well.

**Comment by jayqi** [comment]
Whoops, closed this by accident.

**Comment by frndmg** [comment]
Hi. Looking for some eyes on #244 if anybody has the time. We stumbled upon the same problem and fixed it by patching it but wanted to submit a fix.

> I think append a / to the key if there isn't one in this fallback path—that said, we'll need to double check if that handles the fake directory scenario as well.

It is also checking that condition as well.
