### ISSUE TITLE
Interface difference between CloudPath and its children

### ISSUE THREAD

**Issue by jruere** [drivendataorg/cloudpathlib#234]
In class `CloudPath`, `stat` is a property.

On all of the class children, `stat` is a method. 

This looks like a mistake.

**Comment by pjbull** [comment]
Thanks @jruere, the property is an error on `CloudPath`. We'd accept a PR to remove it. `stat` should be a method in order to follow pathlib: https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat
