### ISSUE TITLE
Add Google cloud storage backend

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#25]
Implementation:
 - [ ] Add cloud provider packages as separate requirements.txt (e.g. [azure](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/requirements/azure.txt))
 - [ ] Client methods implemented. You'll need to implement all of the methods there with the same signatures, and the names should be pretty self explanatory. (Use [azure](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/cloudpathlib/azure/azblobclient.py) or [s3](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/cloudpathlib/s3/s3client.py) as template)
 - [ ] Cloud-specific path methods implemented. (Use [azure](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/cloudpathlib/azure/azblobpath.py) or [s3](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/cloudpathlib/s3/s3path.py) as template)

Tests:
 - [ ] Create testing rig ( examples here: [azure](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/conftest.py#L71-L115) and [s3](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/conftest.py#L118-L154))
 - [ ] Add testing rig to the [set that we run](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/conftest.py#L157)
 - [ ] Create mock client, which mocks the library that interacts with GCS so we can run tests without internet (example for [Azure](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/mock_clients/mock_azureblob.py) and [S3](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/mock_clients/mock_s3.py))
 - [ ] Run tests both live and mocked and ensure they pass
 - [ ] Create tests for any cloud specific methods (example of [S3 here](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/tests/test_s3_specific.py))
 - [ ] Configure live tests to run on github actions (someone with repo admin will have to setup the account and add the creds to the CI secrets)

Docs:
 - [ ] update indicating how to [install cloud packages as extra](https://github.com/drivendataorg/cloudpathlib/blob/master/README.md#installation)
 - [ ] [update tables](https://github.com/drivendataorg/cloudpathlib/blob/8b230c3c7dd339c439a9b6f5af666c745ce15724/docs/make_support_table.py) indicating availability of GCS

**Comment by wolfgangwazzlestrauss** [comment]
I would like to tackle this issue. Are there any contributing rules, specific to your organization, that I should follow?

**Comment by pjbull** [comment]
That would be great, thanks @wolfgangwazzlestrauss!

We've been meaning to put together contribution docs, but I've added a quick overview of what is needed above. Let us know if there are any questions.
