### ISSUE TITLE
Support for `with_stem`

### ISSUE THREAD

**Issue by Gilthans** [drivendataorg/cloudpathlib#287]
Hello!
Today we noticed cloudpathlib doesn't support [`with_stem`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_stem) which was added in python 3.9.
What's the policy on this kind of compatibility (i.e. functions that exist on only some of the supported versions of python)?
Would a PR to introduce this be accepted?

**Comment by pjbull** [comment]
This is released as of `0.16.0`, thanks @Gilthans!
