### ISSUE TITLE
Canonical way to clear file caches

### ISSUE THREAD

**Issue by Gilthans** [drivendataorg/cloudpathlib#294]
Maybe I missed it in the docs, but is there a way to clear all cached files?

I have a use-case where download videos from the cloud, split them to frames, and upload them back. 
There are many videos, and I don't need them once I've split them to frames. Currently I run out of HD memory because there's no way to tell cloudpathlib I don't need those files cached anymore.

I've resorted to `shutil.rmtree(tempfile.gettempdir(), ignore_errors=True)`, but this interferes with other running scripts that use tempfile and also breaks many tests that rely on tempfiles.

Is there a better way?

**Comment by pjbull** [comment]
Yeah, this should exist and I think should be part of #10 

As noted there, the cache temp dir can be cleaned up by deleting the client so it gets garbage collected, which cleans up its cache dir if it is a temporary directory:
https://github.com/drivendataorg/cloudpathlib/blob/ce411fe22b138a183b1b17b815c3141a42e481b1/cloudpathlib/client.py#L44-L47

You could also do something like manually in the meantime `S3Client.get_default_client()._cache_tmp_dir.cleanup()`; or, if you set the cache dir yourself, `shutil.rmtree(S3Client.get_default_client(). _local_cache_dir)`.

**Comment by pjbull** [comment]
Going to close this for now in favor of #10

**Comment by pjbull** [comment]
@Gilthans Updates here were just released! See documentation here: https://cloudpathlib.drivendata.org/stable/caching/#clearing-the-file-cache
