### ISSUE TITLE
Set local_cache_dir from environment variable?

### ISSUE THREAD

**Issue by indigoviolet** [drivendataorg/cloudpathlib#352]
If I want a persistent cache, I can set `CLOUPATHLIB_FILE_CACHE_MODE`. But I then have to pass a `local_cache_dir` in code - why not allow this to also be set from the environment?

**Comment by pjbull** [comment]
Thanks @indigoviolet, good point. We should allow specifying a `CLOUDPATHLIB_DEFAULT_CACHE_DIR`.

We should check for this in in `Client` instantiation and use it if present. I think precedence should be:
 - `local_cache_dir` if passed
 - fallback to `CLOUDPATHLIB_DEFAULT_CACHE_DIR` if available
 - fallback to `TemporaryDirectory` like we do now

Would be happy to accept a PR if you're so inclined. PR should include tests and docs.

**Comment by indigoviolet** [comment]
Thanks @pjbull, I will try to do that.

Another point I noticed was that there isn't a clean way to set up persistence/local_cache_dir while being agnostic to the type of path via AnyPath -> CloudPath. Do you have a suggestion for how to do that?

**Comment by pjbull** [comment]
> Another point I noticed was that there isn't a clean way to set up persistence/local_cache_dir while being agnostic to the type of path via AnyPath -> CloudPath. Do you have a suggestion for how to do that?

Yep, that should be doable with `set_as_default_client`.

For example:

```python
from cloudpathlib import AnyPath, S3Client

s3 = S3Client(local_cache_dir="./data")
s3.set_as_default_client()

cp = AnyPath("s3://test-bucket/file.txt")
cp.client._local_cache_dir
#> PosixPath('data')
```

Docs here:
https://cloudpathlib.drivendata.org/v0.15/api-reference/client/#cloudpathlib.client.Client.set_as_default_client

**Comment by pjbull** [comment]
This has beed added and shipped @indigoviolet. Try install `0.16.0` with `pip` if you want to experiment with it and confirm
