### ISSUE TITLE
CloudPath resolve/absolute/samefile/parts don't handle trailing slash consistently or like pathlib

### ISSUE THREAD

**Issue by indigoviolet** [drivendataorg/cloudpathlib#357]
```python
In [45]: bucket = CloudPath("gs://foo")

In [46]: bucket_slash = CloudPath("gs://foo/")

In [47]: bucket.samefile(bucket_slash)
Out[47]: False

In [48]: bucket.absolute(), bucket_slash.absolute()
Out[48]: (GSPath('gs://foo'), GSPath('gs://foo/'))

In [49]: bucket.resolve(), bucket_slash.resolve()
Out[49]: (GSPath('gs://foo'), GSPath('gs://foo/'))

In [50]: bucket.parts == bucket_slash.parts
Out[50]: True
```

Path:

```
In [57]: from pathlib import Path

In [58]: Path("/foo/").absolute()
Out[58]: PosixPath('/foo')
```

**Comment by indigoviolet** [comment]
In that case, isn't the `parts` method incorrect?

**Comment by jayqi** [comment]
What would you expect to be the correct output of `parts`?

Because the cloud storage services don't actually have `/` behave as a separator, splitting on `/` into parts isn't a thing that makes sense. So, unfortunately, I don't think there is an obvious right way to parts to behave. If you have any feedback here on what _feels_ more intuitive, we'd appreciate hearing it.

**Comment by indigoviolet** [comment]
IMO, the most useful thing would be to ignore the distinction between `a/` and `a`, ie treat prefixes ending in delimiters as folders, for example, [like the S3 console does](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-folders.html). 

It seems to me that a user would be more likely to prefer this behavior than one that maintains this distinction at the cost of `absolute()`, `samefile()` etc not working like in `Path`. Then `parts` can retain its current behavior (returning "folders"). 

I would probably introduce a method like `sameprefix` to capture the current behavior if someone really needed it.
