### ISSUE TITLE
Update pytest-cases dependency to main package

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#368]
Waiting for [this PR](https://github.com/smarie/python-pytest-cases/pull/312) to get merged and released then update `requirements-dev.txt` to use the official package.

TODO: Add an issue to change this once it is merged.

_Originally posted by @pjbull in https://github.com/drivendataorg/cloudpathlib/pull/364#discussion_r1349609194_

**Comment by jayqi** [comment]
The fix was released yesterday. It was part of [3.7.0](https://github.com/smarie/python-pytest-cases/releases/tag/3.7.0) although we're already up to [3.8.0](https://github.com/smarie/python-pytest-cases/releases/tag/3.8.0)—I guess the maintainer blazed through a backlog of PRs.
