### ISSUE TITLE
Avoid making mtime checks if force_overwrite_to_cloud is set

### ISSUE THREAD

**Issue by Gilthans** [drivendataorg/cloudpathlib#379]
Hey there,
I noticed that when uploading files, even if `force_overwrite_to_cloud` is set, local + cloud mtime of the file are still calculated, even though they are effectively ignored.
Usually this is a minor performance overhead, but it can have a large impact when uploading a directory with many small files (like an image pyramid for example).
Since this does not affect functionality at all, I think this is an easy win!

I'll submit a PR soon, LMK if I missed anything

**Comment by pjbull** [comment]
Fixed by #380.
