### ISSUE TITLE
Support anonymous through boto to work with public S3 assets 

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#38]
Here's a first pass that could go in `__init__`.

The big downside is that it does a try-except with an actual network call. Ideally, there would be a way in `boto3` just to check if no creds were configured, and if not fall back to trying UNSIGNED.

```python
        # fallback to trying anonymous "UNSIGNED" requests, which can be used
        # if assets are public
        try:
            self.client.list_buckets()
        except NoCredentialsError:
            self.client = self.sess.client('s3', config=Config(signature_version=UNSIGNED))

        try:
            list(self.s3.buckets.limit(1))
        except NoCredentialsError:
            self.s3 = self.sess.resource("s3", config=Config(signature_version=UNSIGNED))
```

**Comment by jayqi** [comment]
I think the AWS CLI requires you to explicitly pass `--no-sign-request` to do UNSIGNED. It seems reasonable to me that we do the same, and have a parameter with the same name. 

If it's annoying, then we could try to do it automatically in the future and have some kind of `"auto"` setting?

**Comment by pjbull** [comment]
Great, I think a `no_sign_request` kwarg to the client is a good solution for now.
