### ISSUE TITLE
Support file: ?

### ISSUE THREAD

**Issue by pprados** [drivendataorg/cloudpathlib#401]
It's sympathic to use cloudpathlib with url `file:`.

**Comment by pjbull** [comment]
I'd be open to at least a simple shortcut implementation that assumes anything after `file://` you can hand off to `pathlib`.

One question is: if you start with a file URI, do you want a file URI back from all of the methods or is a `Path` object enough (and consumers can call the `Path.as_uri()` method if they need to)?

Here's a way to go to a `Path` from a file that is reported as generally working.
https://github.com/python/cpython/issues/91504#issuecomment-1100257658

That said, to my eye there do seem to be some idiosyncrasies about the specification for file URIs that may break. See: https://en.wikipedia.org/wiki/File_URI_scheme

Resources:
 - [related discussion with Python devs](https://discuss.python.org/t/file-uris-in-python/15600/7)
 - [related Python issue with potential implementations](https://github.com/python/cpython/issues/91504)

**Comment by pprados** [comment]
The id is, with an environment variable only, I can choose the URL.
file: for test, s3: or other for real files. So, the entire API of cloudpathlib must be implemented, with `.read_text()` etc.
The same code must be run.

**Comment by pjbull** [comment]
@pprados, you can now use `file:` with `AnyPath` in the latest version of cloudpathlib on PyPI (0.18.0). See the docs here:
https://cloudpathlib.drivendata.org/stable/anypath-polymorphism/#file-uri-scheme
