### ISSUE TITLE
Copy should be able to take local file to cloud

### ISSUE THREAD

**Issue by GeorgePearse** [drivendataorg/cloudpathlib#417]
```python
path = AnyPath(<some-local-path>)
path.copy(<some-cloud-path>
```

Fails, because path has already been resolved to a posixpath, would be nice if you could copy from cloud to local, and back.

**Comment by pjbull** [comment]
It would be nice, but this is a Python issue (they should add a copy method that supports any library that implements the pathlib interface).

For technical and maintenance reasons, we won't create and maintain a wrapper class for local paths.

There's currently no generic `copy(A, B)` method that just works with any kind of path it gets called with. https://github.com/drivendataorg/cloudpathlib/issues/189 Tracks implementing something like that, or you can implement in the meantime with some code that does subclass checks.

**Comment by GeorgePearse** [comment]
Great answer, and thanks for being so fast!
