### ISSUE TITLE
Incorrect detection of directories in `AzureBlobPath`

### ISSUE THREAD

**Issue by M0dEx** [drivendataorg/cloudpathlib#444]
Currently, the detection of whether a given path points to a blob (file) or a directory is based mostly on the presence of its metadata:
https://github.com/drivendataorg/cloudpathlib/blob/08b018b36f90f89003e0c9e5ebd19030b41c2433/cloudpathlib/azure/azblobclient.py#L152-L172

This is not correct, as directories can have non-empty metadata present (and in newer versions of Azure Blob Storage API they almost always do), which leads to incorrect `is_file` and `is_dir` results.

**Comment by pjbull** [comment]
This should be part of the ADLS Gen2 support released now in [v0.19.0](https://pypi.org/project/cloudpathlib/) if you want to upgrade and test your use case
