### ISSUE TITLE
`AzureBlobPath.iterdir()` is slow for directories with a high level of nesting

### ISSUE THREAD

**Issue by M0dEx** [drivendataorg/cloudpathlib#446]
`AzureBlobPath.iterdir()` is terribly slow for directories with a high level of nesting, even if most of the blobs are not returned.

This is due to how the current implementation handles non-recursive iteration over a directory, needing to filter *all* of the nested blobs returned by the `list_blobs` function on the `BlobServiceClient`:
https://github.com/drivendataorg/cloudpathlib/blob/08b018b36f90f89003e0c9e5ebd19030b41c2433/cloudpathlib/azure/azblobclient.py#L181-L226

There is another function on the client - `walk_blobs`, which has a parameter allowing for non-recursive iteration over a directory, which might provide a significant performance uplift.

Furthermore, the current implementation does not allow for recursive listing of *containers*, which might be a bit unexpected and currently throws a runtime error.

**Comment by pjbull** [comment]
This should be part of the ADLS Gen2 support released now in [v0.19.0](https://pypi.org/project/cloudpathlib/) if you want to upgrade and test your use case
