### ISSUE TITLE
`AzureBlobPath.rmtree()` sometimes fails and needs to be called again

### ISSUE THREAD

**Issue by M0dEx** [drivendataorg/cloudpathlib#448]
In certain scenarios, `AzureBlobPath.rmtree()` can fail and needs to be called again to finish removing the nested file structure. Even after some investigation, we have been unable to pinpoint and reproduce the issue reliably. We suspect the reason might be some sort of a race condition on the side of the Azure Blob Storage API.

**Comment by pjbull** [comment]
This should be part of the ADLS Gen2 support released now in [v0.19.0](https://pypi.org/project/cloudpathlib/) if you want to upgrade and test your use case
