### ISSUE TITLE
Add typing overloads to `CloudPath.open()`

### ISSUE THREAD

**Issue by 0xbe7a** [drivendataorg/cloudpathlib#465]
Currently, the return type of `CloudPath.open()` is always `IO[Any]`. This differs from `pathlib.Path.open()`, which returns more specific types like `TextIOWrapper`, `FileIO`, `BufferedRandom`, `BufferedWriter`, `BufferedReader`, `BinaryIO`, or `IO[Any]` depending on arguments such as `mode`, `buffering`, and `encoding`. The more specific return types are useful for catching typing issues where a library expects a file handle in binary or text mode, specified as `IO[bytes]` or `IO[str]`, respectively. With the current behavior, passing a file handle returned by `CloudPath.open()` often requires using `typing.cast()` or `# type: ignore`.

Here’s an example illustrating the current behavior compared to `pathlib.Path.open()`:

```python
from pathlib import Path
from cloudpathlib import CloudPath

cloud_path = CloudPath("s3://bucket/key")  # type: ignore
local_path = Path("test.txt")

with local_path.open("w") as f:
    reveal_type(f)  # Revealed type: io.TextIOWrapper

with local_path.open("wb") as f:
    reveal_type(f)  # Revealed type: io.BufferedWriter

with cloud_path.open("w") as f:
    reveal_type(f)  # Revealed type: typing.IO[Any]

with cloud_path.open("wb") as f:
    reveal_type(f)  # Revealed type: typing.IO[Any]
```

**Comment by pjbull** [comment]
Thanks @0xbe7a, this is released now in [v0.19.0](https://pypi.org/project/cloudpathlib/) if you want to upgrade and test your use case
