### ISSUE TITLE
API for creating a cloud file by uploading it

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#58]
We have `download_to` to make it easy to copy a file from the cloud to the local filesystem. We don't have an equivalent `upload` or `upload_from` or `copy_from`  (naming is hard) method to easily create a cloud file from a local one.

E.g

```python
# path that does not exist yet
p = CloudPath("az://container/dir/new_file.txt")

#  copies "my_local_text_file.txt" to the path specified by p
p.upload("my_local_text_file.txt")
```

**Comment by jayqi** [comment]
I like `upload_from`. It has symmetry with `download_to`. We also want to distinguish uploading a local file vs. copying from another cloud path (#108).
