### ISSUE TITLE
CloudPath.download_to doesn't work if src is file and destination is directory

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#74]
If the source if a file and destination is a directory, we should make the `_download_file` destination into `destination / self.name`.

From the traceback:
```
~/code/cloudpathlib/cloudpathlib/cloudpath.py in download_to(self, destination)
    533         destination = Path(destination)
    534         if self.is_file():
--> 535             self.backend._download_file(self, destination)
    536         else:
    537             destination.mkdir(exist_ok=True)
```

**Comment by genziano** [comment]
Hello,

while working on Issue #108 I stumbled on this one, and I think that it would help to fix this one first!
It seems a quick one, shall I go for it?
