### ISSUE TITLE
Add `AnyPath` class that will dispatch to either local or cloud

### ISSUE THREAD

**Issue by pjbull** [drivendataorg/cloudpathlib#77]
Just was working on some data pipeline code where it would be useful to be able to seamlessly pass either a cloud or a local path and have things just get handled happily.  

For example, we could replace code that looks like this
```python
DATA_ROOT = os.getenv("DATA_ROOT")

if DATA_ROOT.startswith("s3"):
    DATA_ROOT = S3Path(DATA_ROOT)
else:
    DATA_ROOT = Path(DATA_ROOT)
```

with code that look like this:
```python
DATA_ROOT = AnyPath(os.getenv("DATA_ROOT"))
```

**Comment by jayqi** [comment]
Another argument in favor of making it a class rather than a function is that we can then support having it as a polymorphic type declaration for Pydantic model fields, per #126
